# Eager Execution
eager execution能够使用Python 的debug工具、数据结构与控制流。并且无需使用placeholder、session，计算结果能够立即得出。它将tensor表现得像Numpy array一样，和numpy的函数兼容（注意：比较tensor应使用tf.equal而非==）。还能避免lazy loading的问题。

参考：https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/programmers_guide/eager.md

In [1]:

from __future__ import absolute_import, division, print_function
import tensorflow as tf

tf.enable_eager_execution() #必须放在程序开头

In [2]:
tf.executing_eagerly()

x = [[2.]]
m = tf.matmul(x, x)

print("hello,{}".format(m))

hello,[[4.]]


Eager execution works nicely with NumPy. NumPy operations accept tf.Tensor arguments. TensorFlow math operations convert Python objects and NumPy arrays to tf.Tensor objects. The tf.Tensor.numpy method returns the object's value as a NumPy ndarray.

In [3]:
a = tf.constant([[1, 2],[3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [4]:
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [5]:
# Operator overloading is supported
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [6]:
# Use NumPy values
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [7]:
# Obtain numpy value from a tensor:
print(a.numpy())

[[1 2]
 [3 4]]


tfe = tf.contrib.eager
这个模块中包含了graph execution
,比较推荐在实际运用中使用tfe。也可以换个形式，写为import

import tensorflow.contrib.eager as tfe