# tensorflow operations

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

sess = tf.InteractiveSession()

### tf.cond()    

类似a？b：c
例：out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)

### tf.greater(x, y)  

x>y 返回 tf.true

### tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

从均匀分布中返回随机值

In [3]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

-0.5930238


### tf.case()

In [8]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_uniform([], minval=-1, maxval=1)
y = tf.random_uniform([], minval=-1, maxval=1)
f1 = lambda: x + y
f2 = lambda: x - y
out = tf.case([(tf.less(x, y), f1)], default = f2)
print(sess.run(out))

0.83686113


### tf.equal(x, y)  

按元素返回bool型

In [5]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1], [0, 1, 2]], name = "x")
y = tf.zeros_like(x, name = "y")
out = tf.equal(x, y)
print(sess.run(out))

[[ True False False]
 [ True False False]]


### tf.where(）

找出tensor里所有True值的index

### tf.gather(x,out)

输出x中位置为out的tensor

In [9]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
30.97266006,  26.67541885,  38.08450317,  20.74983215,
34.94445419,  34.45999146,  29.06485367,  36.01657104,
27.88236427,  20.56035233,  30.20379066,  29.51215172,
33.71149445,  28.59134293,  36.05556488,  28.66994858])

y = tf.fill([20], value = 30.0, name = 'y')
out = tf.where(tf.greater(x, y))
print(sess.run(out))
print(sess.run(tf.gather(x, out)))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


### tf.range()

### tf.diag()

对角矩阵

In [10]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

x = tf.range(1, limit = 7)
print(sess.run(tf.diag(x)))


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### tf.matrix_determinant()

返回方阵的行列式

In [13]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

x = tf.random_normal([10, 10])
print(sess.run(tf.matrix_determinant(x)))

433.3985


### tf.unique( x,  out_idx=tf.int32, name=None)
注意结果有两个

y[idx[i]] = x[i] for i in [0, 1,...,rank(x) - 1]

For example:

tensor 'x' is [1, 1, 2, 4, 4, 4, 7, 8, 8]

y, idx = unique(x)

y ==> [1, 2, 4, 7, 8]

idx ==> [0, 0, 1, 2, 2, 2, 3, 4, 4]



In [14]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y, idx = tf.unique(x)
print(sess.run([y, idx]))

[array([ 5,  2,  3, 10,  6,  4,  1,  0,  9]), array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8])]


### tf.reduce_sum()

计算输入tensor元素的和，或者安照reduction_indices指定的轴进行求和

tf.reduce_prod(), tf.reduce_min(), tf.reduce_max(), tf.reduce_mean(), tf.reduce_all(), tf.reduce_any()...

In [35]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
tf.set_random_seed(1234)
x = tf.random_uniform([300])
y = tf.random_uniform([300])
out = tf.cond(tf.less(tf.reduce_mean(tf.subtract(x, y)), 0.0), lambda:tf.square(x - y), lambda:tf.reduce_sum(tf.abs(x - y)))
print(sess.run(out))

96.40262
